<script lang="ts">
  import { writable } from "svelte/store";
  import { goto } from "$app/navigation";
  import { slide } from "svelte/transition";
  import { page } from "$app/state";
  import { onMount } from "svelte";

  // popup states
  let showPopup = false;
  let showErrorPopup = false;
  let errorMessage = "";
  let popupTimeout: ReturnType<typeof setTimeout> | null = null; // Code copied from https://stackoverflow.com/questions/51040703

  // prevent user from writing
  const loading = writable(false);

  function popup(isShown: (isShown: boolean) => boolean, ms = 3000) {
    isShown(true);
    if (popupTimeout !== null) {
      clearTimeout(popupTimeout);
    }
    popupTimeout = setTimeout(() => isShown(false), ms);
  }

  onMount(() => {
    if (page.url.searchParams.get("loginRequired")) {
      popup(isShown => showPopup = isShown);
    }
  });

  // use custom error message for people to understand better
  function showError(msg: string) {
    errorMessage = msg;
    popup(isShown => showErrorPopup = isShown);
  }

  let username = "";
  let password = "";

  async function handleSubmit(event: Event) {
    // prevent user from submitting after clicking login button
    event.preventDefault(); // https://developer.mozilla.org/en-US/docs/Web/API/Event/preventDefault

    if (!username || !password) {
      showError("Please enter username and password");
      return;
    }

    loading.set(true);

    try {
      // api fetch from https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch
      const res = await fetch("/api/auth", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ action: "login", username, password }),
      });

      const data = await res.json();

      if (res.ok && data.message === "Login successful") {
        const role = username[0];
        let redirect = "/";
        if (role === "S") {
          redirect = "/enrollment?loginSuccess=1";
        }
        else if (role === "T") {
          redirect = "/management?loginSuccess=1";
        }
        else if (role === "A") {
          redirect = "/admin?loginSuccess=1";
        }
        goto(redirect);
      } else {
        showError(data.error || "Invalid Username or Password");
      }
    } catch {
      showError("Something went wrong. Please try again later.");
    } finally {
      loading.set(false);
    }
  }
</script>

<style>
  .title {
    display: flex;
    justify-content: center;
    align-items: center;
    white-space: nowrap;
  }
  .login-text {
    display: inline-block;
    transition: .2s;
  }
</style>

{#if showPopup}
  <div
    class="glass-popup popup-f"
    transition:slide={{ duration: 300 }}
  >
    <span>❌ You must be logged in to do that!</span>
    <button class="close-btn" on:click={() => showPopup = false}>&times;</button>
  </div>
{/if}

{#if showErrorPopup}
  <div
    class="glass-popup popup-f"
    transition:slide={{ duration: 300 }}
  >
    <span>❌ {errorMessage}</span>
    <button class="close-btn" on:click={() => showErrorPopup = false}>&times;</button>
  </div>
{/if}

<form
  on:submit={handleSubmit}
  class="glass max-w-md w-full p-8 space-y-6 text-white"
>
  <h2 class="text-3xl font-bold text-center mb-6">
    <div class="title">
      <span class="login-text">Login</span>
    </div>
  </h2>

  <div>
    <!-- 'for' is required for a11y_label_has_associated_control https://svelte.dev/docs/svelte/compiler-warnings#a11y_label_has_associated_control -->
    <!-- svelte-ignore a11y_label_has_associated_control -->
     <!-- above code is generated by VSCode Quick Fix option to ignore a11y_label_has_associated_control -->
    <label class="block text-sm font-semibold mb-2">Username</label>
    <input
      id="username"
      type="text"
      placeholder="Enter username"
      required
      class="w-full px-4 py-2 rounded-md bg-gray-800 text-white focus:outline-none focus:ring-2 focus:ring-indigo-500"
      bind:value={username}
    />
  </div>

  <div>
    <!-- svelte-ignore a11y_label_has_associated_control -->
    <label class="block text-sm font-semibold mb-2">Password</label>
    <input
      id="password"
      type="password"
      placeholder="Enter password"
      required
      class="w-full px-4 py-2 rounded-md bg-gray-800 text-white focus:outline-none focus:ring-2 focus:ring-indigo-500"
      bind:value={password}
    />
  </div>

  <button
    type="submit"
    class="w-full py-2 mt-4 bg-indigo-600 rounded-md font-semibold hover:bg-indigo-700 transition focus:outline-none focus:ring-2 focus:ring-indigo-500"
  >
    {#if $loading} 
      Logging in... 
    {:else} 
      Login 
    {/if}
  </button>
</form>